config/routes.rb
Nomade::Application.routes.draw do
  require 'subdomain' 

  

  resources :fotos
  resources :imobiliaria

  resources :categoria_placas

  resources :sessions, :only => [:new, :create, :destroy, :opcoes]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/opcoes', :to => 'sessions#opcoes'

  resources :usuarios
  resources :tipo_placas
  match '/placas/fotos_placa/' => 'placas#fotos_placa', :as => "fotos_placa", :via => [:get]
  match '/placas/list' => 'placas#list', :as => "list", :via => [:get]
  
  match '/placas/infogrupo' => "placas#infogrupo", :as => "infogrupo", :via => [:get]
  
  resources :interesse, :only => [:index]

  resources :placas do
    member do
      get :new_interesse
      get :destroy_interesse
    end
    
    resources :denuncia, :only => [:new, :create]
    
    resources :compartilha, :only => [:new, :create]
    resources :interesse, :only => [:new, :create]
    match "interesse/removerlista", :to => "interesse#destroy", :as =>"removerlista"

    match "info"
    match "detalhe"
    match "edit", :to => "placas#edit"
    match ":desabilita", :to => "placas#destroy", :as =>"desabilita"
  end
  

  
  constraints(Subdomain) do
    match '/' => 'placas#index'
  end
  
  root :to => "placas#index"

  get 'filtros' => 'placas#filtros' 

end

app/models/categoria_placa.rb
# encoding: utf-8

class CategoriaPlaca < ActiveRecord::Base
	has_one :placa
end

app/controllers/categoria_placas_controller.rb
class CategoriaPlacasController < ApplicationController
  # GET /categoria_placas
  # GET /categoria_placas.json
  def index
    @categoria_placas = CategoriaPlaca.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categoria_placas }
    end
  end

  # GET /categoria_placas/1
  # GET /categoria_placas/1.json
  def show
    @categoria_placa = CategoriaPlaca.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria_placa }
    end
  end

  # GET /categoria_placas/new
  # GET /categoria_placas/new.json
  def new
    @categoria_placa = CategoriaPlaca.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria_placa }
    end
  end

  # GET /categoria_placas/1/edit
  def edit
    @categoria_placa = CategoriaPlaca.find(params[:id])
  end

  # POST /categoria_placas
  # POST /categoria_placas.json
  def create
    @categoria_placa = CategoriaPlaca.new(params[:categoria_placa])

    respond_to do |format|
      if @categoria_placa.save
        format.html { redirect_to @categoria_placa, notice: 'Categoria placa was successfully created.' }
        format.json { render json: @categoria_placa, status: :created, location: @categoria_placa }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria_placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categoria_placas/1
  # PUT /categoria_placas/1.json
  def update
    @categoria_placa = CategoriaPlaca.find(params[:id])

    respond_to do |format|
      if @categoria_placa.update_attributes(params[:categoria_placa])
        format.html { redirect_to @categoria_placa, notice: 'Categoria placa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria_placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_placas/1
  # DELETE /categoria_placas/1.json
  def destroy
    @categoria_placa = CategoriaPlaca.find(params[:id])
    @categoria_placa.destroy

    respond_to do |format|
      format.html { redirect_to categoria_placas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categoria_placas_helper.rb
module CategoriaPlacasHelper
end

app/views/categoria_placas/_form.html.haml
= form_for @categoria_placa do |f|
  -if @categoria_placa.errors.any?
    #error_explanation
      %h2= "#{pluralize(@categoria_placa.errors.count, "error")} prohibited this categoria_placa from being saved:"
      %ul
        - @categoria_placa.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/categoria_placas/edit.html.haml
#corpo
  .header_info
    Editar categoria placa
  %p
  = render 'form'

  = link_to 'Show', @categoria_placa
  \|
  = link_to 'Ir para Home', '/'

app/views/categoria_placas/index.html.haml
#corpo
  %h1 Listing categoria_placas
  .header_info
    Lista de categoria placa
  %p
  %table
    %tr
      %th Desc
      %th Image
      %th
      %th
      %th

    - @categoria_placas.each do |categoria_placa|
      %tr
        %td= categoria_placa.image
        %td= categoria_placa.desc
        %td= link_to 'Show', categoria_placa
        %td= link_to 'Edit', edit_categoria_placa_path(categoria_placa)
        %td= link_to 'Destroy', categoria_placa, :confirm => 'Are you sure?', :method => :delete

  %br

  = link_to 'New Categoria placa', new_categoria_placa_path

app/views/categoria_placas/new.html.haml
#corpo
  .header_info
    Nova categoria placa
  %p
  = render 'form'

  = link_to 'Back', categoria_placas_path

app/views/categoria_placas/show.html.haml
#corpo
  %p#notice= notice

  %p
    %b Desc:
    = @categoria_placa.desc
    %b Image:
    = @categoria_placa.image
  = link_to 'Edit', edit_categoria_placa_path(@categoria_placa)
  \|
  = link_to 'Back', categoria_placas_path