config/routes.rb
Nomade::Application.routes.draw do
  require 'subdomain' 

  

  resources :fotos
  resources :imobiliaria

  resources :categoria_placas

  resources :sessions, :only => [:new, :create, :destroy, :opcoes]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/opcoes', :to => 'sessions#opcoes'

  resources :usuarios
  resources :tipo_placas
  match '/placas/fotos_placa/' => 'placas#fotos_placa', :as => "fotos_placa", :via => [:get]
  match '/placas/list' => 'placas#list', :as => "list", :via => [:get]
  
  match '/placas/infogrupo' => "placas#infogrupo", :as => "infogrupo", :via => [:get]
  
  resources :interesse, :only => [:index]

  resources :placas do
    member do
      get :new_interesse
      get :destroy_interesse
    end
    
    resources :denuncia, :only => [:new, :create]
    
    resources :compartilha, :only => [:new, :create]
    resources :interesse, :only => [:new, :create]
    match "interesse/removerlista", :to => "interesse#destroy", :as =>"removerlista"

    match "info"
    match "detalhe"
    match "edit", :to => "placas#edit"
    match ":desabilita", :to => "placas#destroy", :as =>"desabilita"
  end
  

  
  constraints(Subdomain) do
    match '/' => 'placas#index'
  end
  
  root :to => "placas#index"

  get 'filtros' => 'placas#filtros' 

end

app/models/placa.rb
# encoding: utf-8

class Placa < ActiveRecord::Base
	acts_as_gmappable :msg => "Endereço não valido"
	
	belongs_to :tipo_placa
	belongs_to :categoria_placa
	belongs_to :imobiliarium

	has_many :observacaos
	accepts_nested_attributes_for :observacaos, :reject_if => lambda { |a| a[:conteudo].blank? }, :allow_destroy => true
	
	has_many :fotos

	validates_presence_of :desc, :message => " - É um campo obrigatorio."
	validates_presence_of :endereco, :message => " - Digite e/ou arraste o marcador para onde deseja colocar a placa."
	validates_presence_of :valor, :message => " - Não pode ficar em branco."
	validates :valor, :numericality => {:greater_than => 200, :message => "- Deve ser maior que o indicado."}
	validates :valor, :numericality => {:less_than => 1000000, :message => "- Deve ser menor que o indicado."}

	#validates_length_of :obs, :in => 0..3000, :message => " - Esse campo deve ter até 3000 caracteres"

	usar_como_dinheiro :valor
	usar_como_dinheiro :condominio




	def gmaps4rails_address 
		endereco
	end

	def gmaps4rails_infowindow

    end
    
    def gmaps4rails_title
		endereco
    end

	def gmaps4rails_marker_picture

	    if self.categoria_placa.image != nil
    		if self.valid?
    			{
    			"picture" => self.categoria_placa.image,
				"width" => 60,          # string, mandatory
				"height" => 60,          # string, mandatory
				#"marker_anchor" => ,   # array, facultative
				"shadow_picture" => "/images/shadow.png",  # string, facultative
				"shadow_width" => 60,    # string, facultative
				"shadow_height" => 60,   # string, facultative
				#"shadow_anchor" => ,   # string, facultative
				}
			else
		    	{
		    	"picture" => "/images/marker.png",
				"width" => 50,          # string, mandatory
				"height" => 50,          # string, mandatory
				#"marker_anchor" => ,   # array, facultative
				#"shadow_picture" => ,  # string, facultative
				#"shadow_width" => ,    # string, facultative
				#"shadow_height" => ,   # string, facultative
				#"shadow_anchor" => ,   # string, facultative
				}
			end
		else
			{
	    	"picture" => "/images/marker.png",
			"width" => 50,          # string, mandatory
			"height" => 50,          # string, mandatory
			#"marker_anchor" => ,   # array, facultative
			#"shadow_picture" => ,  # string, facultative
			#"shadow_width" => ,    # string, facultative
			#"shadow_height" => ,   # string, facultative
			#"shadow_anchor" => ,   # string, facultative
			}
		end
	end



end

app/controllers/placas_controller.rb
class PlacasController < ApplicationController
  skip_before_filter :login_required, :only => [:filtros, :index, :show, :info ,:fotos_placa, :detalhe, :infogrupo, :new_interesse, :destroy_interesse]
  before_filter :imobiliaria_required, :only => [:new, :edit]

  def filtros
    
    filtros = []
    quartos = []
    tipos = []
    categorias = []

    qx = []
    qts =[]
    q = []
    itens = []

    categorias = Placa.select("categoria_placas.id, categoria_placas.desc ")
                            .joins(:categoria_placa)
                            .group("categoria_placa_id")
    
    # --> aluga/apto --> q1/q2

    #[aluga/vende]
    #filtro[0].aluga
       #[apto/casa]
       #filtro[0].aluga[0].apto
          #[q1/q2]
          #filtro[0].aluga[0].apto[0].q1[0][0]
          #filtro[0].aluga[0].apto[0].q1[0][1]
          #filtro[0].aluga[0].apto[1].q2[0][0]
          #filtro[0].aluga[0].apto[1].q2[0][1]
       #filtro[0].aluga[1].casa
          #filtro[0].aluga[1].casa[0].q1[0][0]
          #filtro[0].aluga[1].casa[0].q1[0][1]
          #filtro[0].aluga[1].casa[1].q2[0][0]
          #filtro[0].aluga[1].casa[1].q2[0][1]
    #filtro[1].vende
       #filtro[1].aluga[0].apto
          #filtro[1].aluga[0].apto[0].q1[0][0]
          #filtro[1].aluga[0].apto[0].q1[0][1]
          #filtro[1].aluga[0].apto[1].q2[0][0]
          #filtro[1].aluga[0].apto[1].q2[0][1]
       #filtro[1].aluga[1].casa
          #filtro[1].aluga[1].casa[0].q1[0][0]
          #filtro[1].aluga[1].casa[0].q1[0][1]
          #filtro[1].aluga[1].casa[1].q2[0][0]
          #filtro[1].aluga[1].casa[1].q2[0][1]

    
    categorias.each{|cat|    

      tipos = TipoPlaca.where('tipo_placas.id in (select tipo_placa_id from placas where categoria_placa_id = ?)',cat.id)

      tipos.each{|tipo|
        
        quartos = Placa.where(:categoria_placa_id => cat.id, :tipo_placa_id => tipo.id, :desabilitado => true).group(:quartos)

        quartos.each{|quarto|
          qx << Placa.where(:categoria_placa_id => cat.id, :tipo_placa_id => tipo.id,:quartos => quarto.quartos, :desabilitado => true)
          q << {'q'+quarto.quartos.to_s => qx.clone}
          qx = []
        }

        qts << {tipo.desc => q.clone}
        q = []
      }


      
      itens << {cat.desc => qts.clone} 
      
      filtros = {"filtros" => itens}

      quartos = []
      qts = []
    }

    render json: filtros.to_json
  end

  def destroy_interesse
    puts "CHAMADO DESTROY"

    lista_interesse_temp = cookies['interesse']
    interesse = params[:id].to_s
    
    if lista_interesse_temp != nil
      placas = lista_interesse_temp.split("-")
      placas.delete(interesse)

      cookies.permanent['interesse'] = { :value => placas.join("-"), :expires => 48.hour.from_now}
    end
    
    respond_to do |format|
      format.json { render json: @placa }
    end

  end

  def new_interesse
    puts "CHAMADO ADD"

    lista_interesse_temp = cookies['interesse']
    interesse = params[:id].to_s
    #interesse = placa.id.to_s
    puts "plca: "+interesse
    if lista_interesse_temp != nil
      
      placas = lista_interesse_temp.split("-").uniq
      if !placas.include?(interesse)
        lista_interesse_temp += "-" 
        lista_interesse_temp += interesse
        
        cookies.permanent['interesse'] = { :value => lista_interesse_temp, :expires => 48.hour.from_now}
        puts "LISTAINTERESSE : "+interesse
        puts "--> "+cookies['interesse']
      end
    else

      lista_interesse_temp = "" 
      cookies.permanent['interesse'] = { :value => interesse, :expires => 48.hour.from_now}
      
      puts "LISTAINTERESSE : "+interesse
      puts "--> "+cookies['interesse']
    end
    #link_to_function(name, "atualiza_mapa()")
    
    respond_to do |format|
      format.json { render json: @placa }
    end

  end

  def infogrupo
    
    grupoid = []

    params[:infogrupo].split(",").each do |id|
      grupoid.push(id)
    end

    @placas = Placa.where("id in (?)", grupoid)
    
    respond_to do |format|
      format.html # infogrupo.html.erb
      format.json { render json: @placa }
    end

  end

  def info
    @placa = Placa.find(params[:placa_id])

    respond_to do |format|
      format.html # info.html.erb
      format.json { render json: @placa }
    end
  end

  # GET /placas/fotos_placa
  # GET /placas/fotos_placa.json
  def fotos_placa
    @placa = Placa.find(params[:placa_id])

    respond_to do |format|
      format.html # fotos_placa.html.erb
      format.json { render json: @placa }
    end
  end

  # GET /placas/list
  # GET /placas/list.json
  def list
    @placas = Placa.where("imobiliarium_id = (?)",@current_usuario.imobiliarium)

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @placas }
    end
  end
    
  # GET /placas
  # GET /placas.json
  def index
    
    if request.subdomain != '' && request.subdomain != nil
      
      formatedrequest = request.subdomain.split('.')[0]

      if formatedrequest != 'www' && formatedrequest != 'nomade'
        @imobiliaria = Imobiliarium.find_by_nome!(formatedrequest);
      end
    end

    filtrar = Hash.new("filtro")
    if params[:quartos] != nil
      filtrar["quartos"] = params[:quartos]
    end
    if params[:valor] != nil    
      filtrar["valor"] = params[:valor]
    end 
    if params[:tipo] != nil    
      filtrar["tipo_placa_id"] = params[:tipo]
    end 
    if params[:categoria] != nil    
      filtrar["categoria_placa_id"] = params[:categoria]
    end 
    if params[:mostrar] != nil    
      filtrar["imobiliarium_id"] = params[:mostrar]
    end 

    sqlquery = " "
    
    filtrar.each_with_index do |(key, value),index|
     
        operador = " = "
        if key.to_s == "valor"  
          operador = " <= "
        end

        if index > 0
          sqlquery = sqlquery +" and "+ key.to_s + operador + value.to_s
        else
          sqlquery = sqlquery +" "+ key.to_s + operador + value.to_s
        end

    end

   
    if filtrar.empty?
     # @placas = Placa.all
      if @imobiliaria != nil
        @placas = Placa.where("desabilitado = 1 and imobiliarium_id = #{@imobiliaria.id}")
      else
        @placas = Placa.where("desabilitado = 1")
      end
    else
      if @imobiliaria != nil
        @placas = Placa.where(sqlquery+ " and desabilitado = 1 and imobiliarium_id = #{@imobiliaria.id}")
      else
        @placas = Placa.where(sqlquery+ " and desabilitado = 1")
      end
    end 

    #@json = @placas.to_gmaps4rails

    @json = @placas.to_gmaps4rails do |placa, marker|
      lista_interesse = cookies['interesse']
      if lista_interesse != nil
        lista_interesse = lista_interesse.split("-").uniq
        if lista_interesse.include?(placa.id.to_s)
          placa.categoria_placa.image = placa.categoria_placa.image.split(".")[0]+"interesse.png"
        end  
      end
      marker.json({ :id => placa.id })
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @json }
    end
  end

  # GET /placas/1
  # GET /placas/1.json
  def show
    @placa = Placa.find(params[:id])

    @json = @placa.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @json }
    end
  end

  def detalhe
    @placa = Placa.find(params[:placa_id])

    respond_to do |format|
      format.html
      format.json { render json: @placa }
    end
  end

  # GET /placas/new
  # GET /placas/new.json
  def new
    @placa = Placa.new
    @placa.tipo = 'default'
    @placa.longitude = '-46.632982'
    @placa.latitude = '-23.550602'
    @placa.categoria_placa = CategoriaPlaca.new
    @placa.valor = '0'
    @placa.condominio = '0'
    @placa.vagas = 0
    @placa.quartos = 1
    @json = @placa.to_gmaps4rails

    3.times { @placa.observacaos.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @placa }
    end
  end

  # GET /placas/1/edit
  def edit
    @placa = Placa.find(params[:placa_id])
    @json = @placa.to_gmaps4rails
  end

  # POST /placas
  # POST /placas.json
  def create
    @placa = Placa.new(params[:placa])
    @placa.imobiliarium = @current_usuario.imobiliarium

    respond_to do |format|
      if @placa.save
        #format.html { redirect_to :controller => 'placas' }
        format.html { redirect_to @placa, notice: 'A Placa foi colocada com sucesso.' }
        format.json { render json: @placa, status: :created, location: @placa }
      else
        @json = @placa.to_gmaps4rails
        format.html { render action: "new" }
        format.json { render json: @json.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /placas/1
  # PUT /placas/1.json
  def update
    @placa = Placa.find(params[:id])

    respond_to do |format|
      if @placa.update_attributes(params[:placa])
        format.html { redirect_to @placa, notice: 'A Placa foi modificada com sucesso.' }
        format.json { head :no_content }
        
      else
        format.html { render action: "edit" }
        format.json { render json: @placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /placas/1
  # DELETE /placas/1.json
  def destroy

    @placa = Placa.find(params[:placa_id])
    #@placa.destroy

    @placa.desabilitado = params[:desabilita];
    @placa.save

    respond_to do |format|
      format.html { redirect_to list_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/placas_helper.rb
module PlacasHelper

	def pegatipos
		@tipos = TipoPlaca.find(:all).collect{|t| [t.desc, t.id]}
    	@tipos.delete_at(0)
    	@tipos
	end

	def pegacategorias
		@categorias = CategoriaPlaca.find(:all).collect{|t| [t.desc, t.id]}
    	@categorias.delete_at(0)
    	@categorias
	end

	def pegaquartos
		[["todos","todos"],["1",1],["2",2],["3",3],["4",4],["5",5]]
	end

	def pegaendereco
      if !@placa.ocultar?
        @placa.endereco
      else
        "oculto"
      end
    end

  def listainteresse(placa)
    lista_interesse_temp = cookies['interesse']
	  
    if lista_interesse_temp != nil
	    placas = lista_interesse_temp.split("-").uniq
	      if !placas.include?(placa.id.to_s)
	        link_to_add_interesse "Adicionar a lista de interesse"
        else
          link_to_rmv_interesse "Remover da lista de interesse"
	      end
    else
      link_to_add_interesse "Adicionar a lista de interesse"
    end
  end

end

app/views/placas/_form.html.haml
#mapedit
  - if params[:id] == nil
    = gmaps("markers" => {"data" => @json, "options" => { "draggable" => true}}, "map_options" => {"libraries" => ["places"], "processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 13  })
  - else
    = gmaps("markers" => {"data" => Placa.find(params[:id]).to_gmaps4rails, "options" => { "draggable" => true}}, "map_options" => {"libraries" => ["places"], "processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 13  })
%br
= form_for @placa do |f|
  -if @placa.errors.any?
    #error_explanation
      %h2= "#{pluralize(@placa.errors.count, "erro")} - verifique as informações para que a placa seja colocada:"
      %ul
        - @placa.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "Endereço"
    = f.text_field :endereco
    = f.label "Ocultar"
    = f.check_box :ocultar 
  .field
    = f.label "Descrição"
    %br
    = f.text_area :desc, :rows=>6, :cols=>80
  .field
    = f.label "Tipo de imóvel"
    = f.select :tipo_placa_id, pegatipos, {:multiple => false}
  .field
    = f.label "Categoria do imóvel"
    = f.select :categoria_placa_id, pegacategorias, {:multiple => false}
  .field
    = f.label "Número de quartos"
    = f.number_field :quartos
  .field
    = f.label "Vagas na garagem"
    = f.number_field :vagas 
  .field
    = f.label "Andar"
    = f.number_field :andar 
  .field
    = f.label "Valor"
    = f.text_field :valor 
  .field
    = f.label "Condominio"
    = f.text_field :condominio 
  %fields
    = f.fields_for :observacaos do |builder|
      = render "observacao_fields", :f => builder
  .field
    = link_to_add_fields "Adicionar mais uma observação", f, :observacaos
  .field
    = f.hidden_field :latitude
  .field
    = f.hidden_field :longitude
  .actions
    = f.submit 'Colocar a placa', :id =>"send", :class => 'botao'

app/views/placas/_observacao_fields.html.haml
.field
  = f.label :conteudo, "Observação"
  = f.text_field :conteudo
  = f.hidden_field :_destroy
  = link_to_remove_fields "Remover", f

app/views/placas/_opcoes.html.haml
#sitelinks
  %ul
    %li
      = link_to 'Cadastrar Placa', new_placa_path 
    - if @current_usuario == nil
      %li
        = link_to 'Crie seu usuario', new_usuario_path
    - else
      - if @current_usuario.imobiliarium == nil
        %li
          = link_to 'Cadastrar imobiliaria', new_imobiliarium_path 
      - else
        %li
          = link_to 'Editar imobiliaria', edit_imobiliarium_path(@current_usuario.imobiliarium)
        %li
          = link_to 'Listar minhas placas', list_path
    -if @current_usuario != nil
      %li
        = '['+@current_usuario.login+']'
        = link_to 'Logout', logout_path
    - else
      %li    
        //= link_to 'Login', login_path(:modal=>1), :remote => true
        = link_to 'Login', login_path
        
  .links_opcoes_left
    .main_text_light
      .sitelink
        = link_to 'Cadastrar Placa', new_placa_path 
        - if @current_usuario == nil
          %br
          = link_to 'Crie seu usuario', new_usuario_path
        - else
          - if @current_usuario.imobiliarium == nil
            %br
            = link_to 'Cadastrar imobiliaria', new_imobiliarium_path 
          - else
            %br
            = link_to 'Editar imobiliaria', edit_imobiliarium_path(@current_usuario.imobiliarium)
            %br
            = link_to 'Listar minhas placas', list_path
        %br
        %script{:src => "http://connect.facebook.net/pt_BR/all.js#xfbml=1"}
        %fb:like{:href => "http://www.nomade.net.br", :layout => "button_count", :show_faces => "false"}
        -if @current_usuario != nil
          = '['+@current_usuario.login+']'
          = link_to 'Logout', logout_path
          %br
        - else
          //= link_to 'Login', login_path(:modal=>1), :remote => true
          = link_to 'Login', login_path
          %br
        = link_to 'Follow', 'http://www.twitter.com/buscanomade', :target => "_blank"
        = link_to image_tag('/images/tw_logo2.png'), 'http://www.twitter.com/buscanomade', :target => "_blank"
        %br

app/views/placas/detalhe.html.haml
#corpopaginaplaca
  .header_info
    Detalhes da placa
  .corpo_detalhe
    .destaque_detalhe
      %p
        = @placa.desc
      %p  
        = pegaendereco
      %p  
        R$
        = @placa.valor
      %p
        Código:
    .coluna_esquerda
      .carrossel_fotos
        - if @placa.fotos.any?
          = image_tag @placa.fotos[0].imagem_url.to_s, :class => 'img_principal_placa', :id => 'mainImg'
          .fotos_placa  
            %ul#mycarousel_detalhe.jcarousel-skin-tango
              - @placa.fotos.each do |foto|
                %li
                  = link_to image_tag(foto.imagem_url(:thumb).to_s), foto.imagem_url.to_s, :title => foto.descricao, :class => 'link_fotos_detalhe'
      
      %ul.botoes_placa_detalhe
        %li.add_lista
          = link_to 'Adicionar na lista de interesses', '/'
        %li.compartilha_email
          = link_to 'Compartilhar por email', '/'
      .sobre_imovel
        .header
          Sobre o imóvel
        .conteudo
          %p
            = @placa.obs
          %p
            %b Quartos:
            = @placa.quartos
          %p
            %b Andar:
            = @placa.andar
          %p
            %b Vagas na garagem:
            = @placa.vagas
      
      .valores
        .header
          Valores
        .conteudo
          %p
            %b Preço:
            %span
              R$
              = @placa.valor
          %p
            %b Condomínio:
            %span
              R$
              = @placa.condominio
      

    .coluna_direita
      .imobiliaria_info
        .logo
          = link_to image_tag(@placa.imobiliarium.imagem_url(:thumb).to_s), @placa.imobiliarium.site, :target => "_blank"
        .texto
          = link_to @placa.imobiliarium.nome, @placa.imobiliarium.site, :target => "_blank", :class => "nome_imobiliaria"
          %p
            = @placa.imobiliarium.telefone
        
      .fazer_proposta
        .header
          Fazer Proposta
        .campos
          %p 
            Nome:
          %p
            Email:
          %p
            Telefone:
          %p
            Comentário:

app/views/placas/edit.html.haml
#corpopagina
  .header_info
    Alterar placa do imóvel
  %p
  Busque aqui: 
  = text_field_tag :location_search, nil, :size => 100, :type => "search", :placeholder => "Busque pelo endereço aqui" 

  = render 'form'
%br
%br

app/views/placas/fotos_placa.html.haml
.conteudo
  .descricao_foto
    %b Descrição:
    %label.lbl_desc_foto 
    = @placa.fotos[0].descricao
  = image_tag @placa.fotos[0].imagem_url.to_s, :class => 'img_principal_placa', :id => 'mainImg'
  .fotos_placa  
    %ul#mycarousel.jcarousel-skin-tango
      - @placa.fotos.each do |foto|
        %li
          .foto_placa
            = link_to image_tag(foto.imagem_url(:thumb).to_s), foto.imagem_url.to_s, :title => foto.descricao, :class => 'link_fotos'

app/views/placas/index.html.haml
#mapa
  #logo
  #popupteste
    #opcoes-modal
      =render 'opcoes'

  #infobox
    .main_text_light
      .sitelink
        %p
          = link_to 'Contato', 'contato'
        %p
          = link_to 'Sobre', 'sobre'

        %script{:src => "http://connect.facebook.net/pt_BR/all.js#xfbml=1"}
        %fb:like{:href => "http://www.nomade.net.br", :layout => "button_count", :show_faces => "false"}
        = link_to image_tag('/images/tw_logo2.png'), 'http://www.twitter.com/buscanomade', :target => "_blank"
        = link_to '@nomadeonline', 'http://www.twitter.com/buscanomade', :target => "_blank"
  #topbox
    = text_field_tag :location_search, nil, :size => 60, :type => "text", :class => "campo_pesquisa", :placeholder => "Busque pelo endereço"
    #border2
    #menu
  #sliderbox
    #border
    - if params[:minhas] != nil
      = hidden_field_tag :minhas, 1
    #categoria
      - CategoriaPlaca.all.each do |t| 
        - if t.desc != "todos"
          = radio_button_tag "optcategoria", t.id
          = label_tag t.desc
    %br
    #tipo  
      Tipo:
      = select_tag "selector_tipo", {:multiple => false}
      / = select_tag "selector_tipo", options_for_select(TipoPlaca.all.collect {|t| [ t.desc, t.id ] }, {:multiple => false})
    %br
    #quartos
      Quartos:
      = select_tag "selector_quartos", options_for_select(pegaquartos), :multiple => false
    %br
    #valor  
      Valor Limite:
      = select_tag "selector_valor", options_for_select([]), :multiple => false
      - if @current_usuario != nil
        - if @current_usuario.imobiliarium != nil
          %br
          Mostrar:
          = select_tag "selector_mostrar", options_for_select([["todos", "todos"], ["Minhas placas", @current_usuario.imobiliarium.id]]), :multiple => false

  = hidden_field_tag 'currentsel', 'teste' 
  = gmaps("markers" => {"data" => @json, "options" => { :raw => '{ animation: google.maps.Animation.DROP }', "draggable" => false, "zoomOnClick" => false, "do_clustering" => true, "clusterer_gridSize" => 50, "clusterer_maxZoom" => 25 } },"map_options" =>{ :raw => '{panControl: false, backgroundColor: "#BBEBC3", mapTypeControlOptions: { style: google.maps.MapTypeControlStyle.DEFAULT}}', "libraries" => ["places"],"processing" => "json", "auto_adjust" => false, "auto_zoom" => false, "zoom" => 12 ,"center_latitude" => -23.550602, "center_longitude" => -46.632982 } )

app/views/placas/info.html.haml
.conteudo
  %p
    .showcompartilha
    %b 
      = link_to @placa.imobiliarium.nome, @placa.imobiliarium.site, :target => "_blank"
  %p
    %b Telefone:
    = @placa.imobiliarium.telefone
  %p
    = @placa.tipo_placa.desc
  %p
    %b Numero de quartos:
    = @placa.quartos
  %p
    = @placa.desc
  %p
    %b Endereço:
    = pegaendereco
  %p
    %b Valor:
    R$
    = @placa.valor
  - if @placa.fotos.any?
    #modal-container
      #modal2
        .showfotos
          Exibir fotos do imóvel
  - else
    Não há fotos para desse imóvel
  
  %p
    = link_to 'Ver mais detalhes', placa_detalhe_path(@placa)
  %p
    = listainteresse(@placa)

  .showdenuncia

app/views/placas/infogrupo.html.haml
.conteudo
  %p
    - @placas.each do |placa|
      %p
        = placa.desc
      %p  
        = link_to placa.imobiliarium.nome, placa.imobiliarium.site, :target => "_blank"
      %p
        = link_to 'Ver detalhes', placa_detalhe_path(placa)
      %hr

app/views/placas/list.html.haml
#corpopagina
  .header_info
    Minhas placas
  %p

  %table
    %tr
      %th Status
      %th Descrição
      %th Endereço
      %th Oculto
      %th Tipo
      %th Categoria
      %th Valor
      %th 
      %th
      %th

    - @placas.each do |placa|
      %tr
        - if placa.desabilitado?
          %td= "Abilitado"
        - else
          %td= "Desabilitado"
        %td= placa.desc
        %td= link_to placa.endereco, placa
        - if placa.ocultar?
          %td="Oculto"
        -else
          %td="Visivel"
        %td= placa.tipo_placa.desc
        %td= placa.categoria_placa.desc
        %td= placa.valor
        %td= link_to 'Alterar', placa_edit_path(placa)
        - if placa.desabilitado?
          %td= link_to 'Desabilitar', placa_desabilita_path(placa,0)
        - else
          %td= link_to 'Habilitar', placa_desabilita_path(placa,1)
          
          
  %br

app/views/placas/new.html.haml
#corpopagina
  .header_info
    Adicionar placa no imóvel
  %p
  Busque aqui: 
  = text_field_tag :location_search, nil, :size => 100, :type => "search", :placeholder => "Busque pelo endereço aqui" 

  = render 'form'
%br
%br

app/views/placas/show.html.haml
- if @current_usuario != nil
  - if @current_usuario.id == @placa.imobiliarium.usuario.id 
    #corpopaginaplaca
      .header_info
        Detalhes da placa
      .corpo_placa_show
        .informacoes
          %p
            %b Descrição:
            = @placa.desc
          %p
            %b Tipo:
            = @placa.tipo_placa.desc
          %p
            %b Imóvel:
            = @placa.categoria_placa.desc
          %p  
            %b Endereço:
            = @placa.endereco
          %p
            %b Observações:
            %ol
              - for obs in @placa.observacaos
                %li
                  = h obs.conteudo
          %p  
            %b Valor:
            R$
            = @placa.valor

          = link_to 'Alterar', edit_placa_path(@placa)

        .fotos
          .add_foto
            = link_to 'Adicionar uma nova foto', new_foto_path(:placa_id => @placa)

          - if @placa.fotos.any?
            .carrossel_fotos_show
              .fotos_placa_show
                %ul#mycarousel_show.jcarousel-skin-tango
                  - @placa.fotos.each do |foto|
                    %li
                      #thumb_foto_placa_show
                        = image_tag foto.imagem_url(:thumb).to_s, :title => foto.descricao
                      #acoes_foto_placa_show
                        = link_to image_tag('/images/altera_foto.png'), edit_foto_path(foto,:placa_id => @placa), :title => 'Alterar foto'
                        = link_to image_tag('/images/delete_foto.png'), foto, :confirm => 'Você tem certeza?', :method => :delete, :title => 'Apagar foto'