config/routes.rb
Nomade::Application.routes.draw do
  require 'subdomain' 

  

  resources :fotos
  resources :imobiliaria

  resources :categoria_placas

  resources :sessions, :only => [:new, :create, :destroy, :opcoes]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/opcoes', :to => 'sessions#opcoes'

  resources :usuarios
  resources :tipo_placas
  match '/placas/fotos_placa/' => 'placas#fotos_placa', :as => "fotos_placa", :via => [:get]
  match '/placas/list' => 'placas#list', :as => "list", :via => [:get]
  
  match '/placas/infogrupo' => "placas#infogrupo", :as => "infogrupo", :via => [:get]
  
  resources :interesse, :only => [:index]

  resources :placas do
    member do
      get :new_interesse
      get :destroy_interesse
    end
    
    resources :denuncia, :only => [:new, :create]
    
    resources :compartilha, :only => [:new, :create]
    resources :interesse, :only => [:new, :create]
    match "interesse/removerlista", :to => "interesse#destroy", :as =>"removerlista"

    match "info"
    match "detalhe"
    match "edit", :to => "placas#edit"
    match ":desabilita", :to => "placas#destroy", :as =>"desabilita"
  end
  

  
  constraints(Subdomain) do
    match '/' => 'placas#index'
  end
  
  root :to => "placas#index"

  get 'filtros' => 'placas#filtros' 

end

app/models/tipo_placa.rb
# encoding: utf-8

class TipoPlaca < ActiveRecord::Base
  has_one :placa
end

app/controllers/tipo_placas_controller.rb
class TipoPlacasController < ApplicationController
  # GET /tipo_placas
  # GET /tipo_placas.json
  def index
    @tipo_placas = TipoPlaca.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_placas }
    end
  end

  # GET /tipo_placas/1
  # GET /tipo_placas/1.json
  def show
    @tipo_placa = TipoPlaca.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo_placa }
    end
  end

  # GET /tipo_placas/new
  # GET /tipo_placas/new.json
  def new
    @tipo_placa = TipoPlaca.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo_placa }
    end
  end

  # GET /tipo_placas/1/edit
  def edit
    @tipo_placa = TipoPlaca.find(params[:id])
  end

  # POST /tipo_placas
  # POST /tipo_placas.json
  def create
    @tipo_placa = TipoPlaca.new(params[:tipo_placa])

    respond_to do |format|
      if @tipo_placa.save
        format.html { redirect_to @tipo_placa, notice: 'Tipo placa was successfully created.' }
        format.json { render json: @tipo_placa, status: :created, location: @tipo_placa }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_placas/1
  # PUT /tipo_placas/1.json
  def update
    @tipo_placa = TipoPlaca.find(params[:id])

    respond_to do |format|
      if @tipo_placa.update_attributes(params[:tipo_placa])
        format.html { redirect_to @tipo_placa, notice: 'Tipo placa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_placas/1
  # DELETE /tipo_placas/1.json
  def destroy
    @tipo_placa = TipoPlaca.find(params[:id])
    @tipo_placa.destroy

    respond_to do |format|
      format.html { redirect_to tipo_placas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tipo_placas_helper.rb
module TipoPlacasHelper
end

app/views/tipo_placas/_form.html.haml
= form_for @tipo_placa do |f|
  -if @tipo_placa.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tipo_placa.errors.count, "error")} prohibited this tipo_placa from being saved:"
      %ul
        - @tipo_placa.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :desc
    = f.text_field :desc
  .actions
    = f.submit 'Save'

app/views/tipo_placas/edit.html.haml
#corpo
  .header_info
    Editar tipo placa
  %p
  = render 'form'

  = link_to 'Show', @tipo_placa
  \|
  = link_to 'Back', tipo_placas_path

app/views/tipo_placas/index.html.haml
#corpo
  .header_info
    Listar tipo placa
  %p
  %table
    %tr
      %th Desc
      %th
      %th
      %th

    - @tipo_placas.each do |tipo_placa|
      %tr
        %td= tipo_placa.desc
        %td= link_to 'Show', tipo_placa
        %td= link_to 'Edit', edit_tipo_placa_path(tipo_placa)
        %td= link_to 'Destroy', tipo_placa, :confirm => 'Are you sure?', :method => :delete

  %br

  = link_to 'New Tipo placa', new_tipo_placa_path

app/views/tipo_placas/new.html.haml
#corpo
  .header_info
    Novo tipo placa
  %p
  = render 'form'

  = link_to 'Back', tipo_placas_path

app/views/tipo_placas/show.html.haml
#corpo
  %p#notice= notice
  %p
    %b Desc:
    = @tipo_placa.desc

  = link_to 'Edit', edit_tipo_placa_path(@tipo_placa)
  \|
  = link_to 'Back', tipo_placas_path